apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-api-user
spec:
  selector:
    matchLabels:
      app: udagram-api-user
  template:
    metadata:
      labels:
        app: udagram-api-user
    spec:
      containers:
      - name: udagram-api-user
        image: thefl45h/udagram-api-user
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: aws-secret
                key: aws_secret_access_key
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: aws-secret
                key: aws_secret_access_key
          - name: POSTGRES_USERNAME
            valueFrom:
              secretKeyRef:
                name: udagram-secret
                key: postgres_username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: udagram-secret
                key: postgres_password
          - name: POSTGRES_HOST
            valueFrom:
              secretKeyRef:
                name: udagram-secret
                key: postgres_host
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: udagram-secret
                key: jwt_secret
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: udagram-secret
                key: postgres_db
          - name: AWS_BUCKET
            valueFrom:
              configMapKeyRef:
                name: udagram-env
                key: aws_bucket
          - name: AWS_REGION
            valueFrom:
              configMapKeyRef:
                name: udagram-env
                key: aws_region
          - name: AWS_PROFILE
            valueFrom:
              configMapKeyRef:
                name: udagram-env
                key: aws_profile
          - name: URL
            valueFrom:
              configMapKeyRef:
                name: udagram-env
                key: url
          - name: PORT
            valueFrom:
              configMapKeyRef:
                name: udagram-env
                key: port
        ports:
        - containerPort: 8080
